### ISSUE TITLE
Let game configuration be static after build

### ISSUE THREAD

**Issue by bingluen** [CCIP-App/CCIP-Puzzle-Chocolate#1]
### Wishing
Let game configuration be static after build

### Why?
In order to reduce task and complexity during deploy this game.

### Task
- [ ] Create abstract class or parent class to implement data structure which be implemented on `src/store/config.js` previously
    - [ ] Create abstract class or parent class with data structure which store game configuration
    - [ ] Refactoring view to extends abstract class or parent class
        - [ ] `src/view/Bingo.vue`
        - [ ] `src/view/Reward.vue`
- [ ] Read game configuration from file during building static file
