### ISSUE TITLE
Game mode should read from game configuration and be locked on single deployee.

### ISSUE THREAD

**Issue by bingluen** [CCIP-App/CCIP-Puzzle-Chocolate#8]
# Description
Relate to #3 
Load game mode from game configuration instead of `project.json`. And only show the page which match the value of game mode. Others page which is not matched should be hidden(return 404 or others).

# Task
- [ ] Remove `defaultMode` from `project.json`
- [ ] Add `mode` (or others key name which can represent "enabled some game mode page and other page will be hidden") into game configuration
    - [ ] vuex store on `src/store/config`
    - [ ] implement generator (CCIP-App/CCIP-Puzzle-Config-Generator-Chocolate)
    - [ ] document on readme.md
